apiVersion: ecns.easystack.com/v1
kind: Plan
metadata:
  labels:
    app.kubernetes.io/name: plan
    app.kubernetes.io/instance: plan-debug
    app.kubernetes.io/part-of: easystack-eks-op
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/created-by: easystack-eks-op
  name: plan-of-sloth
  namespace: sloth
spec:
  mode: "new"
  k8sVersion: "v1.26.4-es"
  support_python3: false
  lb_enable: false
  cluster_name: "slothcluster"
  ssh_key: "sloth"
  use_float_ip: false
  node_cidr: "10.6.0.0/24"
  other_ansible_opts:
    "cloud_master_vip": "172.46.0.2"
    "registry_ip": "172.46.0.73"
    "webhook_enabled": "false"
    "flannel_interface": "ens3"
    "keepalived_interface": "ens3"
  need_keep_alive:
    - "master"
    - "ingress"
    - "ingress1"
  need_load_balancer: []
  machine_sets:
    - name: "ironic-master"
      role: "master"
      number: 1
      infras:
        - uid: "7d2d"
          availability_zone: "default-az"
          volumes:
            - volume_type: "hdd"
              volume_size: 150
              availability_zone: "default-az"
              index: 1
            - volume_type: "hdd"
              volume_size: 10
              availability_zone: "default-az"
              index: 2
            - volume_type: "hdd"
              volume_size: 5
              availability_zone: "default-az"
              index: 3
          image: "loadbalancer-image-240313-x86_64"
          flavor: "8C-8G"
          replica: 1
          serverMetadata:
            "reserve_instance_type": "normal"
    - name: "sloth-node"
      number: 1
      role: "node"
      infras:
        - uid: "bb85"
          availability_zone: "default-az:ironic.compute.domain.tld.2:5b0118c4-0aa4-4c96-9919-e6beb4e886f2"
          volumes:
            - volume_type: "hdd"
              volume_size: 0
              availability_zone: "default-az:ironic.compute.domain.tld.2:5b0118c4-0aa4-4c96-9919-e6beb4e886f2"
              index: 1
            - volume_type: "hdd"
              volume_size: 0
              availability_zone: "default-az:ironic.compute.domain.tld.2:5b0118c4-0aa4-4c96-9919-e6beb4e886f2"
              index: 2
            - volume_type: "hdd"
              volume_size: 0
              availability_zone: "default-az:ironic.compute.domain.tld.2:5b0118c4-0aa4-4c96-9919-e6beb4e886f2"
              index: 3
          image: "rocky93"
          flavor: "1C-1G"
          replica: 1
          serverMetadata:
            "reserve_instance_type": "baremetal"
  monitor:
    pvc_type: "cinder"
    pvc_cap: "10"
    auto_clear_days: "7d"
  cni_type: "flannel"
  pod_cidr: "10.232.0.0/14"
  svc_cidr: "10.222.0.0/16"
  maxRetryTime: 5
  ansible_plan_auto: true
  deleteVolumeOnTermination: true
  user:
    auth_url: "http://keystone.openstack.svc.cluster.local/v3"
    token: "gAAAAABl9BFjDwHYsGguy4RpePaa9nhGQ-Uf8apN90Xkedq3mdoUdHIYvokPmaLIjZzj-bZkfRVSU6WMvTrFau8MvmcutauQO8LToRPVTE-19g_vFBUOAu4rs6Km0HWiCzK2UqfCuNPapi3SoaHZgLMLmLMGQbeDwIqjGFjrGWHNJgg5h8R6ED0"
    region: "RegionOne"





  # TODO(user): Add fields here
